apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: fake-api
  name: fake-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: fake-api
    spec:
      containers:
      - image: jaxgeller/lwan
        name: fake-api
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /lwan/wwwroot
          name: fake-api-claim0
      restartPolicy: Always
      volumes:
      - name: fake-api-claim0
        persistentVolumeClaim:
          claimName: fake-api-claim0
status: {}
