apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: influxdb
    spec:
      containers:
      - env:
        - name: INFLUXDB_ADMIN_PASSWORD
          value: supersecretpassword
        - name: INFLUXDB_ADMIN_USER
          value: admin
        - name: INFLUXDB_DB
          value: krakend
        - name: INFLUXDB_USER
          value: krakend-dev
        - name: INFLUXDB_USER_PASSWORD
          value: pas5w0rd
        image: influxdb:1.8
        name: influxdb
        ports:
        - containerPort: 8086
        resources: {}
      restartPolicy: Always
status: {}
