apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger
  name: jaeger
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jaeger
    spec:
      containers:
      - image: jaegertracing/all-in-one:latest
        name: jaeger
        ports:
        - containerPort: 16686
        - containerPort: 14268
        resources: {}
      restartPolicy: Always
status: {}
