apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: jwt-revoke
  name: jwt-revoke
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jwt-revoke
    spec:
      containers:
      - image: jwt-revoke
        name: jwt-revoke
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
