apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: krakend-ce
  name: krakend-ce
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: krakend-ce
    spec:
      containers:
      - image: devopsfaith/krakend:1.3.0
        name: krakend-ce
        ports:
        - containerPort: 1234
        - containerPort: 8080
        - containerPort: 8090
        resources: {}
        volumeMounts:
        - mountPath: /etc/krakend
          name: krakend-ce-claim0
      restartPolicy: Always
      volumes:
      - name: krakend-ce-claim0
        persistentVolumeClaim:
          claimName: krakend-ce-claim0
status: {}
