apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: kraken-designer
  name: kraken-designer
spec:
  ports:
  - name: "8787"
    port: 8787
    targetPort: 80
  selector:
    io.kompose.service: kraken-designer
status:
  loadBalancer: {}
