apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: krakend-ce
  name: krakend-ce
spec:
  ports:
  - name: "1234"
    port: 1234
    targetPort: 1234
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "8090"
    port: 8090
    targetPort: 8090
  selector:
    io.kompose.service: krakend-ce
status:
  loadBalancer: {}
