apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: kraken-designer
  name: kraken-designer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kraken-designer
    spec:
      containers:
      - image: devopsfaith/krakendesigner:latest
        name: kraken-designer
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
